config/routes.rb
Campground::Application.routes.draw do
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  
  root to: 'static_pages#home';
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
    
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  
  namespace :common do
    resources :trails
  end
  
  namespace :community do
    resources :updates, only: [ :create]
  end
  
  get 'favorites/show', to: 'corner/favorites#show', as: 'favorites/show'
  get 'favorites/new', to: 'corner/favorites#new', as: 'favorites/new'
  namespace :corner do
    resources :favorites, only: [:create] 
    post 'favorites/add_trail'
    post 'favorites/remove_trail'
    
    match "/logs/:year/:month/:day" => 'logs#show', as: 'logs', constraints: {
      year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ 
    }  
    resources :logs, only: [:new, :create]
  end
  
  get 'invite_user', to: 'users#invite_user', as: 'invite_user'
  namespace :site do
    resources :user_requests, only: [:create]
  end
  get "site/user_requests/:token", to: 'site/user_requests#edit_request', as: "/edit_site_user_request/"
  post "site/user_requests/:token", to: 'site/user_requests#process_request'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  login_id        :string(50)       not null
#  name            :string(50)       not null
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  admin           :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :login_id, :name, :email, :password, :password_confirmation, :current_password
  
  has_secure_password
  
  has_many :updates, 
           class_name: "Community::Update", 
           foreign_key: "author_id",
           dependent: :destroy
  
  has_many :logs, 
           class_name: "Corner::Log", 
           foreign_key: "user_id", 
           dependent: :destroy
           
  has_many :favorite_activities, class_name: "Corner::FavoriteActivity", 
           foreign_key: "user_id", dependent: :destroy
  has_many :activities, class_name: "Common::Activity", through: :favorite_activities
  
  has_many :favorite_trails, class_name: "Corner::FavoriteTrail", 
           foreign_key: "user_id", dependent: :destroy
  has_many :trails, class_name: "Common::Trail", through: :favorite_trails
  
  accepts_nested_attributes_for :trails, reject_if: :all_blank 
  accepts_nested_attributes_for :activities, reject_if: :all_blank   

  VALID_LOGIN_REGEX = /^[A-Za-z\d_]+$/
  validates :login_id, presence: true,
            length: { minimum: 1, maximum: 50 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_LOGIN_REGEX }
  validates :name, presence: true,
            length: { minimum: 1, maximum: 50 }
  VALID_EMAIL_REGEX = /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  VALID_PASSWORD_REGEX = /.*[a-zA-z]+.*\d+.*|.*\d+.*[a-zA-z]+.*/
  validates :password, presence: true,
            length: { minimum: 6 },
            format: { with: VALID_PASSWORD_REGEX }
  validates :password_confirmation, presence: true
  
  before_save do
    login_id.downcase! 
    email.downcase!
  end
  
  # virtual attributes  
  def current_password=(password)
    self.current_password=password if password.present?
  end
  
  
  # class methods
  def self.partial_params
    [["current_password", "password", "password_confirmation"], ["login_id", "name", "email"]]    
  end
  
  def self.password_partial_params?(user_params)
    user_params.keys.eql?(partial_params[0])
  end
  
  # instance methods
  def set_favorite_attributes(new_attribute_ids, attributes, collection)    
    user_attributes = new_attribute_ids.map { |id| collection.find_by_id(id) }    
    self.update_attribute(attributes, user_attributes)     
  end
  
  def update_partial_attributes(user_params)  
    unless self.class.partial_params.include?(user_params.keys)
      self.errors.add("parmeters", "cannot be updated!")
    end
    
    if self.class.password_partial_params?(user_params)
      if self.authenticate(user_params["current_password"]) 
        user_params.delete(:current_password)
      else
        self.errors.add("current_password", "is not correct. User authentication failed")
      end
    end

    unless self.errors.any?
      self.set_partial_attributes(user_params)
    end

    !self.errors.any?
  end


  def set_partial_attributes(user_params)
    if self.validate_partial_attributes(user_params)    
      user_params.keys.each do |key|
        self.update_attribute(key, user_params[key])        
      end
    end      
  end
  
  
  def validate_partial_attributes(user_params)
    self.update_attributes(user_params)
    original_errors = self.errors.dup
    self.populate_errors_for_params(original_errors, user_params) if self.errors.any?
    !self.errors.any?
  end  
    
  
  def populate_errors_for_params(add_errors, user_params)
    self.errors.clear

      add_errors.messages.keys.each do |key|          
        if user_params.has_key?(key)
          add_errors.messages[key].each do |message|
            self.errors.add(key, message)
          end # add error message 
        end #key in user_params        
    end    
  end # populate_errors
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :guest_user, :only => [:new, :create, :invite_user]
  before_filter :authorize_user, :only => [:show, :edit, :update]
  before_filter :account_owner, :only => [:edit, :update]
  
  def show
    @user = User.find_by_id(params[:id])
  end

  def invite_user    
  end
  
  def new
    @user = User.new
  end
  
  def create
    logger.debug params[:user][:email]  
    @user = User.new(params[:user])
    logger.debug @user.email
    if @user.save
      UserMailer.welcome_message(@user).deliver
      log_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
    @page = params[:page] || 1
  end

  def update   
    if @user.update_partial_attributes(params[:user]) 
      if params[:page].present? && params[:page].to_i.eql?(2)
        redirect_to edit_user_path(@user)
      else  
        redirect_to @user
      end
    else
      @page = params[:page]
      render 'edit'
    end
  end

  private
  def account_owner
    @user = User.find_by_id(params[:id])
    unless current_user?(@user)
      redirect_to root_path
      false
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Campground - Profile") %>
<% if @page.to_i.eql?(1) %>
	<h2>Changing Profile</h2>
<% end %>
	
<% if @page.to_i.eql?(2) %>
	<h2>Changing Password</h2>
<% end %>

<div id = "other_links_button">
	<%= link_to "Change favorites", favorites_new_path %>
</div>	

<div class="project_form">
	<%= form_for @user do |f| -%>
	
		<%= render 'shared/error_messages', object: f.object %>

		<% if @page.to_i.eql?(1) %>
			<div>
				<%= f.label :login_id, "Login ID" %>
				<%= f.text_field :login_id  %>						
			</div>

			<div>
				<%= f.label :name, "Name" %>
				<%= f.text_field :name  %>		
			</div>

			<div>
				<%= f.label :email, "Email" %>
				<%= f.text_field :email  %>
			</div>
				
			<div class = "change_password_button">
				<%= link_to "Change password", edit_user_path(@user, page: 2) %>
			</div>	

			<div>
				<%= hidden_field_tag "page", 1 %>
				<%= f.submit "Save Profile" %>			
			</div>
		<% end %>

		<% if @page.to_i.eql?(2) %>
			<div>
				<%= f.label :current_password, "Current password" %>
				<%= f.password_field :current_password  %>						
			</div>
			<div>
				<%= f.label :password, "New password" %>
				<%= f.password_field :password  %>						
			</div>

			<div>
				<%= f.label :password_confirmation, "Confirm new password" %>
				<%= f.password_field :password_confirmation  %>						
			</div>
				
			<div>
				<%= hidden_field_tag "page", 2 %>
				<%= f.submit "Save password" %>			
			</div>
		<% end %>
	<% end -%>	
</div>
 

app/views/users/invite_user.html.erb
<%= provide(:title, "Join Campground") %>
<h2>Get An Invite</h2>

<div class='project_form'>
	<%=  form_tag site_user_requests_path do -%>
		<%= hidden_field_tag "user_request", "get_invite" %>
		<%= hidden_field_tag "back_path", request.url %>
		
		<div>
			<%= label_tag :invite_email, "Email" %>
			<%= text_field_tag :invite_email  %>
		</div>
		
		<%= submit_tag "Send me an invite" %>

	<% end -%>	
</div>

app/views/users/new.html.erb
<% provide(:title, "Join Campground") %>
<h2>Join campground</h2>

<div class="project_form">
	<%= form_for @user do |f| -%>

		<%= render 'shared/error_messages', object: f.object%>

		<div>
			<%= f.label :login_id, "Login ID" %>
			<%= f.text_field :login_id  %>						
		</div>

		<div>
			<%= f.label :name, "Name" %>
			<%= f.text_field :name  %>		
		</div>

		<div>
			<%= f.hidden_field :email %>
			<%= f.label :email, "Email" %>
			<%= f.text_field :email, disabled: true %>
		</div>

		<div>
			<%= f.label :password, "Password" %>
			<%= f.password_field :password  %>
		</div>

		<div>
			<%= f.label :password_confirmation, "Confirm password" %>
			<%= f.password_field :password_confirmation  %>
		</div>

		<div>
			<%= f.submit "Create account" %>			
		</div>

	<% end -%>	
</div>

app/views/users/show.html.erb
<% provide(:title, "Campground - #{@user.name}") %>
<h2>About <%= @user.name %></h2>

<% if current_user?(@user) %>
	<div id = "other_links_button">
		<%= link_to "Change profile", edit_user_path(@user) %>
	</div>	
<% end %>
<div id="user_profile_photo">
	Add a photo
</div>
<div id="user_profile_info">
	<%= @user.email %><br><br>
	Interested in <%= output_with_commas(@user.activities, :name) %>
</div>
<div id="user_profile_updates">
	<h4>Updates by <%= @user.name %></h4>
	<%= render_update_partial(@user.updates) %>
</div>