config/routes.rb
Campground::Application.routes.draw do
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  
  root to: 'static_pages#home';
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
    
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  
  namespace :common do
    resources :trails
  end
  
  namespace :community do
    resources :updates, only: [ :create]
  end
  
  get 'favorites/show', to: 'corner/favorites#show', as: 'favorites/show'
  get 'favorites/new', to: 'corner/favorites#new', as: 'favorites/new'
  namespace :corner do
    resources :favorites, only: [:create] 
    post 'favorites/add_trail'
    post 'favorites/remove_trail'
    
    match "/logs/:year/:month/:day" => 'logs#show', as: 'logs', constraints: {
      year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ 
    }  
    resources :logs, only: [:new, :create]
  end
  
  get 'invite_user', to: 'users#invite_user', as: 'invite_user'
  namespace :site do
    resources :user_requests, only: [:create]
  end
  get "site/user_requests/:token", to: 'site/user_requests#edit_request', as: "/edit_site_user_request/"
  post "site/user_requests/:token", to: 'site/user_requests#process_request'

end

app/views/layouts/_community_pane.html.erb
<div id="user_community">	
	<% div_name = div_for_side_panes %>
	<%= content_tag(:div, class: div_name) do %>
		<%= link_to "Trails", common_trails_path, class: "title_text" %>
	<% end %>
	<%= content_tag(:div, class: div_name) do %>
		<%= link_to "Bazaar", "#", class: "title_text" %>
	<% end %>
	<%= content_tag(:div, class: div_name) do %>
		<%= link_to "Company", "#", class: "title_text" %>
	<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div id="right_links">
		<%= link_to "About", about_path %>
	</div>
	<div id="left_links">
		<%= link_to "Contact", contact_path %>
	</div> 
</footer>	

app/views/layouts/_header.html.erb
<header>
	<% if logged_in? %>
		<%= link_to "Profile", current_user , id: "left_buttons" %>
		<%= link_to "Log out", logout_path, method: :delete, id: "right_buttons" %>
	<% else %>
		<% if params[:controller] != "users" && params[:controller] != "site/user_requests"  %>
			<%= link_to "Join", invite_user_path, id: "left_buttons" %>			
		<% end %> 
		<% if params[:controller] != "sessions" %>
			<%= link_to "Log in", login_path, id: "right_buttons" %>			
		<% end %>
	<% end %>
	<h1><%= link_to image_tag("logo.png", alt: "Logo - Home"), root_path %></h1>
</header>	

app/views/layouts/_individual_pane.html.erb
<div id="user_individual">	
	<% div_name = div_for_side_panes %>
	<%= content_tag(:div, class: div_name ) do %>
		<%= link_to "Favorites", favorites_show_path, class: "title_text" %>
	<% end %>
	<%= content_tag(:div, class: div_name ) do %>
		<%= link_to "Diary", "#", class: "title_text" %>
	<% end %>
	<%= content_tag(:div, class: div_name ) do %>
		<%= link_to "Trips", "#", class: "title_text" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title).empty? ? "Campground" : yield(:title) %></title>	
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/individual_pane' %>

<%= render partial: 'layouts/community_pane' %>
<div id="user_dynamic">
	<%= render partial: 'layouts/header' %>
	<div id="user_display">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "flash_#{key}") %>
		<% end %>
		<%= yield %>		
	</div>
	<%= render partial: 'layouts/footer' %>
</div>

</body>
</html>